server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.53.249.35:3306/littleLife?characterEncoding=UTF-8
    username: root
    password: 123456


xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8081/xxl-job-admin
    accessToken: default_token
    executor:
      appname: xxl-job-littleLife
      port: 9999
      logretentiondays: 30
      address:
      logpath: /data/applogs/xxl-job/jobhandler
      ip:

rocketmq:
  name-server: 120.53.249.35:9876   # rocketMq 服务地址
  producer:
    group: my-group
    send-message-timeout: 3000 # 发送消息超时时间，单位：毫秒。默认为 3000

token:
  # token 值
  value: littlelife123
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: 88aba3c0147afab50d6063adc3bc8a82
  # 令牌有效期（默认30分钟）
  expireTime: 30
